#!/usr/bin/env node
/* Charge the Line — full test suite.
   Usage:  node tests/run_all.js          (everything, about a minute)
           node tests/run_all.js quick    (syntax, balance, guide, short fuzz)
           node tests/run_all.js play human    (pick sections)
   Sections: syntax balance learn variants inject play paths human checks guide stress fuzz
   Exit code 0 = all passed. */
global.window=global.window||{};
const path=require('path'),fs=require('fs'),vm=require('vm'),{execFileSync}=require('child_process');
const ALL=['syntax','balance','learn','variants','inject','ev','def','fill','omp','play','paths','human','checks','guide','stress','fuzz'];
let want=process.argv.slice(2);if(!want.length)want=ALL;if(want.includes('quick'))want=['syntax','balance','learn','guide','fuzz'];
const results=[];let failed=0;const T0=Date.now();
function report(section,name,ok,detail=''){results.push({ok});if(!ok)failed++;console.log(`${ok?'PASS':'FAIL'}  ${section.padEnd(8)} ${name}${detail?'  — '+detail:''}`);}
const quiet=fn=>{const l=console.log;console.log=()=>{};try{return fn();}finally{console.log=l;}};
const html=fs.readFileSync(path.join(__dirname,'..','index.html'),'utf8');
const short=n=>n.length>38?n.slice(0,37)+'…':n;

if(want.includes('syntax')){try{new vm.Script(html.split('<script>')[1].split('</script>')[0]);report('syntax','index.html script compiles',true);}catch(e){report('syntax','index.html script compiles',false,e.message);}
  const ver=(html.match(/APP_VERSION='([^']+)'/)||[])[1],sw=fs.readFileSync(path.join(__dirname,'..','sw.js'),'utf8'),cache=(sw.match(/CACHE = '([^']+)'/)||[])[1];
  report('syntax','service-worker cache matches app version',cache===`charge-the-line-v${ver}`,`app ${ver}, cache ${cache}`);
  {// Milestone 3: the shared core is loaded before the app, listed in the offline cache, and its header hash matches its body (edit without re-hashing = fail)
   const cp=path.join(__dirname,'..','preconnect-core.js');const ct=fs.existsSync(cp)?fs.readFileSync(cp,'utf8'):'';const first=ct.split('\n')[0]||'';const body=ct.slice(first.length+1);
   const want=(first.match(/sha256:([0-9a-f]{64})/)||[])[1];const got=require('crypto').createHash('sha256').update(body,'utf8').digest('hex');const sw4=fs.readFileSync(path.join(__dirname,'..','sw.js'),'utf8');
   const tagOK=html.indexOf('<script src="preconnect-core.js"></script>')>-1&&html.indexOf('<script src="preconnect-core.js"></script>')<html.indexOf('\n<script>\n');
   report('syntax','shared core loaded first, cached offline, header hash matches body',!!ct&&want===got&&sw4.includes("'preconnect-core.js'")&&tagOK,want===got?'hash ok':`hash expected ${got.slice(0,12)}`);}
  {// Milestone 3: due-again spacing and the debrief body are pure functions; prove them here
   const {boot}=require('./qa_mock.js');const {api}=boot();const d=n=>new Date(Date.now()-n*864e5).toISOString();
   const never=api.pcSpacing([]).status==='never',one=api.pcSpacing([{d:d(0),score:90}]),two=api.pcSpacing([{d:d(5),score:90},{d:d(4),score:90}]),miss=api.pcSpacing([{d:d(5),score:90},{d:d(1),score:40}]),due=api.pcSpacing([{d:d(10),score:95}]);
   report('syntax','spacing: 1, 3, 7, 14, 30 days after each clear at 70+; a miss resets; overdue reads as due',never&&one.level===1&&one.dueIn===1&&one.status==='ok'&&two.level===2&&two.status==='due'&&miss.status==='missed'&&due.status==='due'&&due.level===1,`one ${one.status}/${one.dueIn}d, two ${two.status}, miss ${miss.status}, due ${due.status}`);
   const bp=api.pcBestPrev([{d:d(3),score:80},{d:d(1),score:60}]);const h=api.pcDebriefBody({score:90,compare:bp,metrics:[['Rate','110 / min']],feedback:['Late breath'],lessons:[{k:'x',name:'Breaths'}],steps:[{name:'Check pulse',ok:true,at:'0:05'},{name:'Shock',ok:false,missed:true}]});
   report('syntax','debrief body: compare line, metrics table, what cost points, lessons, steps table',bp.best===80&&bp.prev===60&&/Best 80 · last time 60 · new best/.test(h)&&/pc-metrics/.test(h)&&/What cost points/.test(h)&&/data-k="x"/.test(h)&&/pc-steps/.test(h)&&/✗/.test(h));}

  {// Every overlay has a way back (Max, October 3, 2026). The briefing used to offer only "Start mission".
   const {boot}=require('./qa_mock.js');const {api,els}=boot();api.loadCampaign(0);api.showBrief();const open=!els.briefov.classList.contains('hidden');els['brief-back'].onclick();
   {const b3=boot();b3.api.loadCampaign(0);b3.api.showBrief();b3.api.$('brief-go').onclick();b3.api.finish();report('syntax','mission debrief uses Debrief 2.0 (steps table, clean-run line, score count-up)',/pc-steps/.test(b3.els['done-body'].innerHTML)&&/Clean run/.test(b3.els['done-body'].innerHTML)&&b3.els['done-score'].textContent==='100');}
   {const intro=(html.match(/<div class="overlay" id="intro">([\s\S]*?)<\/div><\/div>/)||[])[1]||'';const words=intro.replace(/<[^>]+>/g,' ').trim().split(/\s+/).length;const b5=boot();b5.api.setSetting('contrast','high');
    report('syntax','first-run card is short (the full guide lives under How to play) and the settings sheet is wired',words<120&&/id="howov"/.test(html)&&/id="how-close"/.test(html)&&/id="setov"/.test(html)&&/id="h-set"/.test(html)&&b5.api.settings().contrast==='high'&&!/Barlow/.test(html),`${words} words on the first-run card`);}
   report('syntax','mission briefing has a way back to the menu',open&&els.briefov.classList.contains('hidden')&&!els.menu.classList.contains('hidden')&&api.S.briefing===false&&api.S.running===false);}
{const cm=fs.readFileSync(path.join(__dirname,'..','CLAUDE.md'),'utf8'),rd=fs.readFileSync(path.join(__dirname,'..','README.txt'),'utf8');const cv=(cm.match(/\*\*Current version: ([\d.]+)/)||[])[1],av=(html.match(/APP_VERSION='([^']+)'/)||[])[1];
 report('syntax','the briefing names the shipped version and the README lists the core and the fonts (final sweep M3)',cv===av&&/preconnect-core\.js/.test(rd)&&/fonts\//.test(rd),`briefing ${cv}, app ${av}`);}
  {const lits=[...html.matchAll(/(?:Version |>v)(\d+\.\d+\.\d+)/g)].map(m=>m[1]);report('syntax','intro and menu show the current version',lits.length>=2&&lits.every(v=>v===ver),`found ${lits.join(', ')}; app ${ver}`);}
  {// Milestone 1: fonts are served from this site; nothing loads from Google (offline fidelity + privacy). Every font file exists and is in the offline cache list.
   const sw3=fs.readFileSync(path.join(__dirname,'..','sw.js'),'utf8');const urls=[...html.matchAll(/url\((fonts\/[^)]+)\)/g)].map(m=>m[1]);
   const ok=!/fonts\.googleapis|gstatic\.com/.test(html)&&urls.length>=5&&urls.every(u=>fs.existsSync(path.join(__dirname,'..',u))&&sw3.includes(`'${u}'`));
   report('syntax','fonts served from this site, cached offline, no request to Google',ok,`${urls.length} font files`);}
  {// Milestone 1: the screen stays awake while an activity runs and is released after (stubbed wake lock; the real one is async)
   const {boot}=require('./qa_mock.js');const {api}=boot();let req=0,rel=0;const lock={addEventListener(){},release(){rel++;return Promise.resolve();}};navigator.wakeLock={request(){req++;return {then(f){f(lock);return {catch(){}};}};}};
   try{api.loadCampaign(0);api.showBrief();api.$('brief-go').onclick();}catch(e){report('syntax','screen stays awake during an activity, released after',false,e.message);}
   const a=req>=1;api.showMenu();report('syntax','screen stays awake during an activity, released after',a&&rel>=1&&rel===req,`requests ${req}, releases ${rel}`);delete navigator.wakeLock;}

  report('syntax','offline helper only clears its own old caches (other apps on the domain keep theirs)',/k\.startsWith\('charge-the-line-v'\)/.test(sw));
  {const sw2=fs.readFileSync(path.join(__dirname,'..','sw.js'),'utf8');report('syntax','offline helper never caches anonymous statistics',/goatcounter\\\.com\$\|\(\^\|\\\.\)zgo\\\.at/.test(sw2)||sw2.includes('goatcounter')&&sw2.includes('zgo'));}}
  {// Milestone B (final sweep, M1): the page and the shared core are both network-first with a short wait, bad answers are never saved, installs skip the HTTP cache, and index.html is stored once
   const sw5=fs.readFileSync(path.join(__dirname,'..','sw.js'),'utf8');const coreNF=sw5.includes("netFirst(req, 'preconnect-core.js')")&&/fellBack = Date\.now\(\)/.test(sw5),navNF=/req\.mode === 'navigate'\)\s*\{\s*e\.respondWith\(netFirst/.test(sw5),wait=/const NET_WAIT = (\d+)/.test(sw5)&&+sw5.match(/const NET_WAIT = (\d+)/)[1]<=4000&&/Promise\.race\(\[net, wait\]\)/.test(sw5),okOnly=/if \(r\.ok\) \{ const copy = r\.clone\(\); caches\.open\(CACHE\)\.then\(c => c\.put\(key, copy\)\)/.test(sw5),reload=/cache: 'reload'/.test(sw5),once=!/CORE = \['\.\/'/.test(sw5)&&/'index\.html'/.test(sw5);
   report('syntax','offline helper: page and shared core network-first with a short wait, bad answers never saved, fresh installs skip the HTTP cache, index stored once',coreNF&&navNF&&wait&&okOnly&&reload&&once,`core ${coreNF} nav ${navNF} wait ${wait} ok ${okOnly} reload ${reload} once ${once}`);}


if(want.includes('learn')){const {boot}=require('./qa_mock.js');
  {// the lesson: 12 slides, first-try scoring, no skipping, recorded apart from scenarios
   const {api,els,store}=boot();api.lessonStart();const L=api.LESSON;let skipped=false;
   for(let i=0;i<L.length;i++){const S=api.LS();const before=S.i;api.lessonAct({l:'next'});if(api.LS()&&api.LS().i!==before)skipped=true;const k=L[i].o.findIndex(o=>o[1]==='good');api.lessonAct({l:'ans',k});api.lessonAct({l:'next'});}
   const ex=JSON.parse(store['e102-pump-trainer']).extra||[];report('learn','lesson: all 12 checks right first try scores 100, cannot skip a slide, recorded under extra',!skipped&&ex.length===1&&ex[0].kind==='lesson'&&ex[0].score===100&&api.LS()===null,`score ${ex[0]&&ex[0].score}`);
   const b=boot();b.api.lessonStart();for(let i=0;i<L.length;i++){const bad=L[i].o.findIndex(o=>o[1]!=='good'),good=L[i].o.findIndex(o=>o[1]==='good');b.api.lessonAct({l:'ans',k:bad});b.api.lessonAct({l:'ans',k:good});b.api.lessonAct({l:'next'});}
   const ex2=JSON.parse(b.store['e102-pump-trainer']).extra||[];report('learn','lesson: a wrong first answer on every slide scores 0 (retry still lets you continue)',ex2.length===1&&ex2[0].score===0,`score ${ex2[0]&&ex2[0].score}`);
   const longest=L.filter(s=>{const len=s.o.map(o=>o[0].length);return len[s.o.findIndex(o=>o[1]==='good')]===Math.max(...len);}).length,shortest=L.filter(s=>{const len=s.o.map(o=>o[0].length);return len[s.o.findIndex(o=>o[1]==='good')]===Math.min(...len);}).length;
   report('learn','lesson checks: right answer is not usually the longest or the shortest',longest/L.length<=.45&&shortest/L.length<=.45,`longest ${longest}/${L.length}, shortest ${shortest}/${L.length}`);
   report('learn','every lesson check has exactly one right answer and three distinct options',L.every(s=>s.o.length===3&&s.o.filter(o=>o[1]==='good').length===1&&new Set(s.o.map(o=>o[0])).size===3));}
  {// drills: answer keys recalculated independently from the question text (rule 7), 100 when right, 0 when wrong
   const FL={'1¾"':15.5,'2½"':2,'3"':0.8,'5"':0.08};const r5=x=>Math.round(x/5)*5;let checked=0,bad=[];
   for(let rep_=0;rep_<25;rep_++){const {api}=boot();for(const k of Object.keys(api.DRILLS)){for(const q of api.DRILLS[k].items()){checked++;let want=null;
     if(k==='friction'){const m=q.q.match(/^(\d+) ft of (\S+) hose flowing (\d+) gpm/);want=r5(FL[m[2]]*Math.pow(m[3]/100,2)*(m[1]/100))+' psi';}
     if(k==='pdp'){const m=q.q.match(/^(\d+) ft of (\S+) at (\d+) gpm, (75-psi fog|100-psi fog|smooth bore) nozzle, (ground floor|one floor up|(\d+) floors up)/);const np={'75-psi fog':75,'100-psi fog':100,'smooth bore':50}[m[4]];const fl=m[5]==='ground floor'?0:m[5]==='one floor up'?1:+m[6];want=r5(np+FL[m[2]]*Math.pow(m[3]/100,2)*(m[1]/100)+fl*5)+' psi';}
     if(k==='hydrant'){const m=q.q.match(/Static (\d+) psi. After the first line, residual (\d+) psi/);const d=(m[1]-m[2])/m[1]*100;want=d<=10?'Three more':d<=15?'Two more':d<=25?'One more':'None';}
     if(k==='tank'){const H=x=>{const h=Math.round(x*2)/2;return Math.floor(h)+':'+(h%1?'30':'00')+' min';};let m;
       if(m=q.q.match(/^(\d+)-gallon tank, one line flowing (\d+) gpm\. How long/))want=H(m[1]/m[2]);
       else if(m=q.q.match(/^(\d+)-gallon tank, two lines flowing (\d+) gpm and (\d+) gpm/))want=H(m[1]/(+m[2]+ +m[3]));
       else if(m=q.q.match(/^(\d+)-gallon tank, three lines flowing (\d+), (\d+) and (\d+) gpm/))want=H(m[1]/(+m[2]+ +m[3]+ +m[4]));
       else if(m=q.q.match(/^(\d+)-gallon tank\. One line flows (\d+) gpm for (\d+) minutes?, then a second line opens at (\d+) gpm/)){const used=m[2]*m[3];want=used<+m[1]?H(+m[3]+(m[1]-used)/(+m[2]+ +m[4])):null;}
       else if(m=q.q.match(/^(\d+)-gallon tank, flowing (\d+) gpm\. At minute (\d+) a tanker carrying (\d+) gallons/)){want=m[1]/m[2]>+m[3]?H((+m[1]+ +m[4])/m[2]):null;}
       else if(m=q.q.match(/^(\d+)-gallon tank, flowing (\d+) gpm while a tanker refills it at (\d+) gpm/))want=H(m[1]/(m[2]-m[3]));
       else if(m=q.q.match(/^(\d+)-gallon tank, one line flowing (\d+) gpm for (\d+) minutes\. How many gallons/)){const g=m[1]-m[2]*m[3];want=g>0?g+' gal':null;}}
     if(k==='control'){const key=Object.keys(api.GUIDE_ALL).find(x=>api.GUIDE_ALL[x].what===q.q);want=key?api.GUIDE_ALL[key].name:null;}
     const opts=[q.a,...q.d];if(want!==q.a||new Set(opts).size!==3||q.d.includes(q.a))bad.push(`${k}: ${q.q.slice(0,50)} → ${q.a} (want ${want})`);}}}
   report('learn',`drills: ${checked} generated questions, answer keys match an independent recalculation, three distinct options`,bad.length===0,bad.slice(0,2).join(' | '));
   for(const k of ['friction','pdp','control','hydrant','tank']){const {api,store}=boot();api.drillStart(k);for(let i=0;i<api.QZ().qs.length;i++){const q=api.QZ().qs[i];api.quizAct({q:'ans',i:String(q.ord.indexOf(q.a))});api.quizAct({q:'next'});}const r=api.QZ().score;
     const b=boot();b.api.drillStart(k);for(let i=0;i<b.api.QZ().qs.length;i++){const q=b.api.QZ().qs[i];b.api.quizAct({q:'ans',i:String(q.ord.findIndex(o=>o!==q.a))});b.api.quizAct({q:'next'});}const w=b.api.QZ().score;const ex=JSON.parse(store['e102-pump-trainer']).extra||[];
     report('learn',`${api.DRILLS[k].name}: all right = 100, all wrong = 0, recorded`,r===100&&w===0&&ex.some(x=>x.kind==='drill'&&x.id===k&&x.score===100),`${r} / ${w}`);}
   {const {api}=boot();let n=0;for(let r_=0;r_<20;r_++)for(const k of ['friction','pdp'])for(const q of api.DRILLS[k].items()){const len=[q.a,...q.d].map(x=>x.length);if(len[0]===Math.max(...len)&&len.filter(x=>x===len[0]).length===1)n++;}
     report('learn','numeric drills: the right answer is not usually the longest option',n/(20*2*8)<=.45,`${n} of ${20*2*8}`);}
   {const {api}=boot();let lo=0,sh=0,n=0;for(let r_=0;r_<40;r_++)for(const q of api.DRILLS.tank.items()){n++;const len=[q.a,...q.d].map(x=>x.length);if(len[0]===Math.max(...len)&&len.filter(x=>x===len[0]).length===1)lo++;if(len[0]===Math.min(...len)&&len.filter(x=>x===len[0]).length===1)sh++;}
     report('learn','Tank time: eight questions of every kind (one, two and three lines, a second line opening late, a tanker arriving mid-problem, a refill coming in, gallons left); the right answer is not usually the longest or the shortest option',lo/n<=.45&&sh/n<=.45&&api.DRILLS.tank.items().length===8,`longest ${lo}, shortest ${sh} of ${n}`);}}}

/* boot-based checks run before the play harness is created: a later boot() would swap the harness's document and storage out from under it */
if(want.includes('learn')){const {boot}=require('./qa_mock.js');/* final sweep M3 */
  {// final sweep M3: Pump math is the 21st activity — a set of five or more typed answers is saved as a drill run with statistics; fewer is a quit
   const {api,els}=boot();const W=global.window;const snip=[];W.PCA={begin:(m,a)=>snip.push('begin:'+m+'/'+a),end:d=>snip.push('end:'+d),abandon:()=>snip.push('abandon'),bkt:n=>'score-'+n,err(){}};
   els['b-math'].onclick();for(let i=0;i<5;i++){els.ans.value=String(api.MP().r.total);els['m-check'].onclick();els['m-next'].onclick();}els['m-exit'].onclick();
   const rec=(api.load().extra||[]).find(x=>x.kind==='drill'&&x.id==='math');
   els['b-math'].onclick();els.ans.value='1';els['m-check'].onclick();els['m-exit'].onclick();const n2=(api.load().extra||[]).length;delete W.PCA;
   els['b-progress'].onclick();const prog=/Pump math \(sets of five or more\)<\/td><td>best 100 · 1 run/.test(els.proglist.innerHTML);
   report('learn','pump math: five right answers then Exit save a drill run (100) with start and finish events and a progress row; one answer then Exit is a quit and saves nothing',!!rec&&rec.score===100&&n2===1&&prog&&snip.join()==='begin:ctl/drill-math,end:score-100,begin:ctl/drill-math,abandon',`${snip.join()} · records ${n2} · progress ${prog}`);}
  {// final sweep M3: units read psi and gpm in lower case everywhere except the governor's own PSI / RPM labels
   const all=(html.match(/\bPSI\b/g)||[]).length,gov=(html.match(/Pump PSI|>PSI<|PSI mode|PSI \/ RPM|PSI or RPM|'PSI'/g)||[]).length,gpm=(html.match(/\bGPM\b/g)||[]).length;
   report('learn','units: no upper-case PSI or GPM outside the governor labels (the Pump PSI readout, the PSI button, PSI / RPM modes)',all===gov&&all>=5&&gpm===0,`PSI ${all}, of which governor labels ${gov}; GPM ${gpm}`);}
}
if(want.includes('variants')){const {boot}=require('./qa_mock.js');const VARIANTS=boot().api.VARIANTS;const NZ={lpfog:[75,150],fog100:[100,150],sb1516:[50,185]},FLC2={1.75:15.5,2.5:2,3:0.8,5:0.08};const fl=(d,g,l)=>FLC2[d]*(g/100)*(g/100)*(l/100);
  {// the Guided step text and the crew's band match an independent PDP recalculation for the variant's hose and nozzle (never the app's own pdp())
   const {boot}=require('./qa_mock.js');let bad=[];for(const v of VARIANTS[0]){const b=boot();global.window.FORCE_V={0:v.id};b.api.loadCampaign(0);global.window.FORCE_V=undefined;const [np,gpm]=NZ[v.pre200.noz];const t=Math.round(np+fl(1.75,gpm,v.pre200.len));const st=b.api.CAMP[0].missions[0].steps.find(s=>/^Bring/.test(s.t));
     const m=st&&st.t.match(/(\d+)–(\d+) psi \(PDP (\d+)\)/);if(!m||+m[3]!==t||+m[1]!==t-10||+m[2]!==t+10)bad.push(`${v.id}: expected PDP ${t}, text "${st&&st.t}"`);const ch=b.api.CAMP[0].missions[0].chat;if(ch.lo!==t-10||ch.hi!==t+10)bad.push(v.id+' chat band');
     if(!b.api.S.vtext.includes(v.pre200.len+' ft')||b.api.S.hydCap!==v.hyd||b.api.S.hydBase!==v.hyd)bad.push(v.id+' text/hydrant');}
   report('variants','residential layouts: Guided target and crew band equal an independent PDP recalculation; dispatch names the hose and hydrant',bad.length===0,bad.join(' | '));}
  {// relay: band follows the lay length (20 psi at the far intake plus 5" friction loss, rounded to 5), and the intro quotes the same numbers
   const {boot}=require('./qa_mock.js');let bad=[];for(const v of VARIANTS[4]){const b=boot();global.window.FORCE_V={4:v.id};b.api.loadCampaign(4);global.window.FORCE_V=undefined;const lo=Math.round((20+Math.round(0.08*25*v.lay/100))/5)*5;const m=b.api.CAMP[4].missions[1];const hold=m.steps.find(s=>s.hold);
     if(hold.lo!==lo||hold.hi!==lo+15||m.chat.lo!==lo)bad.push(`${v.id}: band ${hold.lo}-${hold.hi}, expected ${lo}-${lo+15}`);if(!m.intro().includes(`${v.lay} ft`)||!m.intro().includes(`Give them ${lo+5}`))bad.push(v.id+' intro');}
   report('variants','relay layouts: band and intro follow the lay length',bad.length===0,bad.join(' | '));}
  {// random pick covers every layout; Standard layouts always gives A; Real Saves are never varied and keep the default hose; a run records its layout
   const {boot}=require('./qa_mock.js');const b=boot();const seen=new Set();for(let k=0;k<60;k++){b.api.loadCampaign(0);seen.add(b.api.S.variant);}const b2=boot({'e102-pump-trainer':JSON.stringify({name:'',scen:{},math:{right:0,total:0},std:true})});const std=new Set();for(let k=0;k<12;k++){b2.api.loadCampaign(0);std.add(b2.api.S.variant);}
   b.api.loadCampaign(0);const corv=b.api.CAMP.findIndex(c=>/Corvallis/.test(c.name));b.api.loadCampaign(corv);const real=b.api.S.variant===''&&b.api.LINE.pre200.len===200&&b.api.LINE.pre200.noz==='lpfog';
   report('variants','random pick covers every layout; Standard layouts always gives A; Real Saves keep the default hose',seen.size===3&&std.size===1&&std.has('A')&&real,`seen ${[...seen].sort().join('')}, standard ${[...std].join('')}`);}}

if(want.includes('inject')){const {boot}=require('./qa_mock.js');
  {// scenario spacing comes from the shared core now
   const d=n=>new Date(Date.now()-n*864e5).toISOString();const {api}=boot({'e102-pump-trainer':JSON.stringify({name:'',scen:{},math:{right:0,total:0},log:[{i:0,score:90,tier:0,d:d(0)},{i:1,score:90,tier:0,d:d(10)},{i:2,score:90,tier:0,d:d(5)},{i:2,score:40,tier:0,d:d(1)}]})});
   const a=api.dueInfo(0),b=api.dueInfo(1),c=api.dueInfo(2),n=api.dueInfo(3);report('inject','menu due text follows the core spacing: cleared today → next in 1 d, overdue → Due for review, a miss → Try again, never → Not yet cleared',a.txt==='Next in 1 d'&&!a.due&&b.txt==='Due for review'&&b.due&&c.txt==='Try again'&&c.due&&n.txt==='Not yet cleared'&&n.due,`${a.txt} / ${b.txt} / ${c.txt} / ${n.txt}`);}
  {global.__loc={search:'?drill=hydrant'};const {api,els}=boot();global.__loc={search:'?drill=nope'};const b=boot();global.__loc=undefined;
   report('inject','daily-drill deep link: ?drill=hydrant opens Hydrant math on load with the intro hidden; an unknown id is ignored',!!api.QZ()&&api.QZ().cfg&&api.QZ().cfg.id==='hydrant'&&!els.quizov.classList.contains('hidden')&&els.intro.classList.contains('hidden')&&!b.api.QZ(),`title ${els['qz-title'].textContent}`);}
  {// Milestone 6: sound and haptics through the shared core
   const fakeAudio=()=>{const log=[];const AC=function(){this.currentTime=0;this.state='running';this.destination={};this.resume=()=>{};this.createOscillator=()=>({type:'sine',frequency:{value:0},connect(){},start(t){log.push({f:this.frequency.value,t});},stop(){}});this.createGain=()=>({gain:{setValueAtTime(){},exponentialRampToValueAtTime(){}},connect(){}});};const buzz=[];const F={log,buzz,fs:()=>log.map(x=>x.f),arm(){global.window=global.window||{};global.window.AudioContext=AC;navigator.vibrate=p=>{buzz.push(JSON.stringify(p));return true;};}};F.arm();return F;};
   const F=fakeAudio();const {api,els}=boot();F.arm();api.setSetting('sound','on');api.loadCampaign(0);els['brief-go'].onclick();F.log.length=0;F.buzz.length=0;api.ding(5,'test penalty');const bad=F.fs().includes(220)&&F.buzz.includes('[30,40,30]');F.log.length=0;api.S.mission=api.CAMP[0].missions.length-1;api.finish();const done=F.fs().join().includes('523,659,784');
   const G=boot();F.arm();G.api.setSetting('sound','off');F.log.length=0;F.buzz.length=0;G.api.loadCampaign(0);G.els['brief-go'].onclick();G.api.ding(5,'test');const quiet=F.log.length===0&&F.buzz.includes('[30,40,30]');delete global.window.AudioContext;delete navigator.vibrate;
   report('inject','sound and haptics: a penalty plays the bad tone and buzzes, finishing chimes; with sound off the buzz still works and nothing plays',bad&&done&&quiet,`bad ${bad}, done ${done}, quiet ${quiet}`);}
  {// Drill Night (Milestone 7): with a session on, layouts stay standard, the instructor button is on without the switch, and every saved run names who was up and the instructor
   const start=new Date().toISOString();const {api,els}=boot({'preconnect-drill':JSON.stringify({on:true,inst:'Max',roster:['Jo','Sam'],who:'Jo',start})});const bar=els['pc-drill'];
   let allA=true;for(let k=0;k<12;k++){api.loadCampaign(0);if(api.S.variant!=='A')allA=false;}const fab=!els['inst-fab'].classList.contains('hidden');els['brief-go'].onclick();api.S.mission=api.CAMP[0].missions.length-1;api.finish();
   api.lessonStart();for(const sl of api.LESSON){api.lessonAct({l:'ans',k:sl.o.findIndex(o=>o[1]==='good')});api.lessonAct({l:'next'});}
   const p=api.load();const lg=p.log[p.log.length-1],ex=p.extra[p.extra.length-1];const on=api.instOn(),binst=els['b-inst'].textContent,bstd=els['b-std'].textContent;const b2=boot();b2.api.loadCampaign(0);b2.els['brief-go'].onclick();b2.api.S.mission=b2.api.CAMP[0].missions.length-1;b2.api.finish();const plain=b2.api.load().log[0];
   report('inject','Drill Night: standard layout, instructor button on, bar shows who is up, runs and lessons credited to that person with the instructor and the night; no session means no stamping',allA&&fab&&!bar.classList.contains('hidden')&&/Up: Jo/.test(bar.innerHTML)&&(lg.who||[])[0]==='Jo'&&lg.inst==='Max'&&lg.night===start&&(ex.who||[])[0]==='Jo'&&ex.inst==='Max'&&on&&/on \(Drill Night\)/.test(binst)&&/standard \(Drill Night\)/.test(bstd)&&plain.who===undefined&&plain.night===undefined,`log who ${lg.who}, inst ${lg.inst}`);}
  {// the panel: hidden unless instructor mode is on and a scenario is active; opening it pauses, closing resumes, freeze holds the clock until resumed; unavailable injects are disabled; a run with injects is marked in the record and the debrief
   const {api,els}=boot();api.setTier(0);const fabHiddenOff=els['inst-fab'].classList.contains('hidden');api.setInst(true);const fabHiddenMenu=els['inst-fab'].classList.contains('hidden');api.loadCampaign(0);const fabShown=!els['inst-fab'].classList.contains('hidden');els['brief-go'].onclick();els['s-pump'].onclick();for(let k=0;k<4;k++)api.tick(.25);
   api.instOpen();const paused=!api.S.running&&!els.instov.classList.contains('hidden');const html=els['inst-body'].innerHTML;const burstDisabled=/data-inj="burst" disabled/.test(html),govEnabled=/data-inj="gov">/.test(html);api.instClose();const resumed=api.S.running;
   api.instOpen();api.instAct('freeze');const frozen=!api.S.running&&api.INSTHOLD()&&els['inst-fab'].textContent.startsWith('Frozen');for(let k=0;k<4;k++)api.tick(.25);const still=!api.S.running;api.instOpen();api.instAct('resume');const back=api.S.running&&!api.INSTHOLD();
   api.instOpen();api.instAct('gov');const injected=api.S.fault==='gov'&&api.S.mode==='rpm'&&api.S.injects.length===1&&api.S.running;
   report('inject','instructor panel: hidden until on and active, pauses while open, freeze holds the clock, unavailable injects disabled',fabHiddenOff&&fabHiddenMenu&&fabShown&&paused&&burstDisabled&&govEnabled&&resumed&&frozen&&still&&back&&injected,`fab ${fabHiddenOff&&fabHiddenMenu&&fabShown}, pause ${paused}/${resumed}, freeze ${frozen}/${still}/${back}, disabled ${burstDisabled}/${govEnabled}, injected ${injected}`);}
  {// progress screen lists lesson and drill bests, and the CSV carries them
   const {api,els}=boot({'e102-pump-trainer':JSON.stringify({name:'',scen:{0:{best:90,runs:2,last:new Date().toISOString(),tier:1,level:1}},math:{right:3,total:4},log:[{i:0,score:90,tier:1,d:new Date().toISOString(),v:'B'}],extra:[{kind:'lesson',id:'lesson',score:92,d:new Date().toISOString()},{kind:'drill',id:'hydrant',score:75,d:new Date().toISOString()},{kind:'drill',id:'hydrant',score:100,d:new Date().toISOString()}]})});
   els['b-progress'].onclick();const h=els.proglist.innerHTML;els['b-export'].onclick();const csv=global.__blob||'';
   report('inject','progress screen: lesson and drill bests, layouts seen, pump math; CSV has the same rows',/Pump lesson<\/td><td>best 92 · 1 run/.test(h)&&/Hydrant math<\/td><td>best 100 · 2 runs/.test(h)&&/layouts B/.test(h)&&/75% of 4/.test(h)&&/Friction loss<\/td><td>—/.test(h)&&/"Pump lesson","","1","92",/.test(csv)&&/"Hydrant math","","2","100",/.test(csv)&&/"Friction loss","","0","","",/.test(csv),'');}}



const env=(want.some(x=>['balance','variants','inject','ev','def','fill','omp','play','paths','human','stress','fuzz'].includes(x)))?require('./qa.js'):null;
if(want.includes('variants')){const {CAMP,VARIANTS}=env.env.api;
  // every named layout of every regular scenario completes on Guided and Recall, and a Chaos run too; the briefing names the layout
  for(const i of Object.keys(VARIANTS)){let ok=0,n=0,perfect=0,named=0;for(const v of VARIANTS[i])for(const tier of [0,1,2]){n++;const r=quiet(()=>env.play(+i,tier,'good',{variant:v.id}));if(r.ok)ok++;if(r.ok&&r.score===100&&tier<2)perfect++;if(r.variant===v.id)named++;}
    report('variants',`${short(CAMP[i].name)}: every layout completes on every tier`,ok===n&&named===n&&perfect===VARIANTS[i].length*2,`${ok}/${n} complete, ${perfect}/${VARIANTS[i].length*2} perfect on Guided and Recall`);}
  {// a finished run records its layout, and a run without injects is not marked as an instructor run
   const r=quiet(()=>env.play(0,0,'good',{variant:'B'}));const log=env.env.api.load().log||[];const lastLog=log[log.length-1]||{};
   report('variants','the training record keeps the layout of each run',r.ok&&lastLog.v==='B'&&!lastLog.inst,`logged ${lastLog.v}`);}}

if(want.includes('inject')){const {CAMP}=env.env.api;
  {// each inject applies on Guided through the instructor panel, the crew calls it, and the mission still completes
   const cases=[[0,'burst',0],[0,'gov',0],[0,'hydrant',1,1],[3,'strainer',2],[0,'lowtank',0]];const out=[];let ok=0;
   for(const [ci,f,mi,at] of cases){const r=quiet(()=>env.play(ci,0,'good',{inject:{mission:mi,at:at||12,f}}));const good=r.ok&&r.injected===true&&(f==='lowtank'||r.faults.includes(f));if(good)ok++;out.push(`${f} ${good?'ok':'FAIL'} (${r.ok?'completed':'stuck at '+r.stuck}, injected ${r.injected}, score ${r.score})`);}
   report('inject','every inject lands on Guided and the engineer can still finish the mission',ok===cases.length,out.join(' | '));}
  {// a run with an inject is marked in the record and the debrief names the inject
   const p=quiet(()=>env.play(0,0,'good',{inject:{mission:0,at:12,f:'gov'}}));const log=env.env.api.load().log||[];const marked=(log[log.length-1]||{}).inst===1&&/Instructor injects/.test(env.env.api.$('done-body').innerHTML);
   report('inject','a run with an inject is marked in the record and named in the debrief',p.ok&&marked,`completed ${p.ok}, marked ${marked}`);}}

if(want.includes('ev')){const api=env.env.api;const EV=api.CAMP.findIndex(c=>c.ev);const run=(o)=>quiet(()=>env.play(EV,1,'good',Object.assign({variant:'A'},o||{})));
  report('ev','the EV fire is scenario 11 (appended, so older records keep their numbers) with three layouts',EV===10&&api.VARIANTS[10].length===3&&api.CAMP[10].name==='EV fire on a county road');
  {const r=run({choiceAt:{'Water supply on arrival':'bad'}});report('ev','waiting to call for tankers: the officer calls late, the tank runs dry with the line flowing and the battery rekindles; the scenario can still be finished',r.ok&&r.score<=55&&api.S.rekN>=1,`score ${r.score}, rekindles ${api.S.rekN}`);}
  {const r=run();report('ev','tankers on arrival: the tank lasts until the tanker is hooked up and the battery never comes back (100)',r.ok&&r.score===100&&api.S.rekN===0,`score ${r.score}`);}
  {const r1=run({choiceAt:{'Disabling the vehicle':'never'}}),r2=run({choiceAt:{'Disabling the vehicle':'never','Getting water to the cells':'never'}});report('ev','the ERG "never" items cost 30 each (cutting the orange high-voltage cables, prying the battery cover)',r1.ok&&r1.score===70&&r2.ok&&r2.score===40,`${r1.score} / ${r2.score}`);}
  {const decs=[];api.CAMP[10].missions.forEach(m=>m.steps.forEach(s=>{if(s.dec&&!Object.getOwnPropertyDescriptor(s.dec,'opts').get)decs.push(s.dec);}));const all=JSON.stringify(decs.map(d=>[d.opts,d.real]));
   report('ev','every "never" option quotes the guide; the Guide 147 lines are there (large amounts of water on the battery, the maker\'s emergency guide first, never cut high-voltage cabling, do not pierce, cut, pry or dismantle, reignition up to weeks later, thermal imaging); tow and storage marked per department SOP',decs.every(x=>x.opts.filter(o=>o.r==='never').every(o=>/The guide says/.test(o.why)))&&decs.some(x=>x.opts.some(o=>o.r==='never'))&&/large amounts of water, sprayed directly onto the battery/.test(all)&&/manufacturer's emergency response guide/.test(all)&&/never cut high-voltage or medium-voltage cabling/.test(all)&&/do not pierce, cut, pry or dismantle/.test(all)&&/up to weeks later/.test(all)&&/thermal imaging/.test(all)&&/per department SOP \/ to confirm/.test(all));}
  {const up=path.join(__dirname,'..','..','upwind','index.html');if(fs.existsSync(up)){const u=fs.readFileSync(up,'utf8');const liev=(u.match(/ liev:\{[^\n]*/)||[''])[0],liion=(u.match(/ liion:\{[^\n]*/)||[''])[0];
    report('ev','the Guide 147 lines match Upwind\'s checked materials table (UN3556 and UN3480, Guide 147, read by Max from the printed ERG2024)',/guide:147/.test(liev)&&/un:'3556'/.test(liev)&&/never cut high-voltage or medium-voltage cabling/.test(liev)&&/large amounts of water, sprayed directly onto the battery/.test(liev)&&/do not pierce, cut, pry or dismantle/.test(liion)&&/up to weeks later/.test(liion)&&/2026-10-07 Max, ERG2024 printed book/.test(liev));}}
  {global.window.FORCE_V={10:'A'};api.setTier(0);api.loadCampaign(10);global.window.FORCE_V=undefined;const S=api.S;api.$('brief-go').onclick();api.tick(0.25);api.$('dec-opts').onclick({target:{closest:()=>({dataset:{i:String(api.DEC().s.dec.opts.findIndex(o=>o.r==='good'))}})}});api.$('dec-go').onclick();
   const n0=api.RADIO_N();api.$('s-supply').onclick();const refused=!S.supply&&api.RADIO_N()===n0+1;
   S.pump=true;S.kd=true;S.flame=false;S.heat=60;S.valves.front.open=0;let smokeAt=null,flameAt=null;for(let i=0;i<80;i++){api.tick(0.25);if(smokeAt===null&&S.smokeSaid)smokeAt=i/4;if(flameAt===null&&S.flame)flameAt=i/4;}
   report('ev','shutting the line down to stretch the tank is allowed (rule 14): the pack reheats, white smoke first, then flame, and it costs 10; connecting a tanker line before a tanker is there is refused (nothing to connect to)',refused&&smokeAt!==null&&flameAt!==null&&smokeAt<flameAt&&S.rekN===1&&S.incidents.some(x=>/battery rekindled/.test(x)),`smoke ${smokeAt}s, flame ${flameAt}s`);}
  {global.window.FORCE_V={10:'A'};api.setTier(1);api.loadCampaign(10);global.window.FORCE_V=undefined;const S=api.S;api.$('brief-go').onclick();S.pump=true;S.mode='psi';S.set=170;S.kd=true;S.flame=false;S.heat=60;S.valves.front.open=25;S.decisions=[];for(let i=0;i<20;i++)api.tick(0.25);const tr=api.DEC();if(tr){api.$('dec-opts').onclick({target:{closest:()=>({dataset:{i:'0'}})}});api.$('dec-go').onclick();}
   for(let i=0;i<80;i++)api.tick(0.25);report('ev','gating the line down to a quarter turn to stretch the tank is not enough water: the pack reheats and rekindles too',S.rekN>=1&&S.heat>0,`rekindles ${S.rekN}, heat ${Math.round(S.heat)}`);}
  {global.window.FORCE_V={10:'B'};api.setTier(1);api.loadCampaign(10);global.window.FORCE_V=undefined;const S=api.S;S.tank=540;api.CAMP[10].missions[1].onStart();const o=api.CAMP[10].missions[1].steps[0].dec.opts;const h=Math.round(540/250*2)/2;const want=Math.floor(h)+':'+(h%1?'30':'00')+' min';
   report('ev','the tank-math card is computed from the gauge and the line (540 gal at 250 gpm), checked against an independent recalculation, with three distinct options',o.filter(x=>x.r==='good').length===1&&o.find(x=>x.r==='good').t===want&&new Set(o.map(x=>x.t)).size===3,o.map(x=>x.t).join(' / '));}
  {global.window.FORCE_V={10:'A'};api.setTier(1);api.loadCampaign(10);global.window.FORCE_V=undefined;const S=api.S;api.$('brief-go').onclick();const ff0=api.ffStep();
   S.mission=3;api.CAMP[10].missions[3].onStart();const sd=api.stepsDone();sd.length=0;api.CAMP[10].missions[3].steps.forEach(()=>sd.push(false));sd[0]=true;sd[1]=true;S.running=true;S.briefing=false;S.heat=0;S.kd=true;S.flame=false;const t0=S.t;const on=api.ffStep()===2;api.ffRun();
   report('ev','fast-forward is offered only on a waiting step (not on arrival), runs the same clock and stops the moment the white smoke comes back',ff0===null&&on&&S.smoke2&&S.t-t0>=19&&S.t-t0<=26&&S.heat>0,`offered ${on}, ran ${(S.t-t0).toFixed(1)} s`);}
  {const r=run({inject:{f:'tanker',mission:1,at:8}});const r2=run({inject:{f:'tanker',mission:1,at:8},choiceAt:{'Tanker delayed':'bad'}});
   report('ev','instructor: the tanker delay splices a decision card; asking for an engine to nurse you keeps the battery wet (100), gating the line down costs points',r.ok&&r.score===100&&r.injected===true&&r2.ok&&r2.score<100,`${r.score} / ${r2.score}`);}
  {const r=run({inject:{f:'flare',mission:2,at:6}});report('ev','instructor: a flare-up after knockdown is answered by the water already on the battery, and the run is marked',r.ok&&r.injected===true&&(api.load().log||[]).slice(-1)[0].inst===1);}
  {const r=run();const b=api.$('done-body').innerHTML;report('ev','the debrief carries the Guide 147 lines, says the gallons are modeled and links to Upwind\'s lithium-ion fire, Layout A',/From Guide 147 \(ERG2024\), UN3556/.test(b)&&/modeled/.test(b)&&/\.\.\/upwind\/\?scn=liion&amp;v=A/.test(b));}
  {const r=quiet(()=>env.play(10,0,'good',{variant:'C'}));report('ev','layout C (the garage beside the SUV): a second line protects the exposure and the tank still lasts until the tanker',r.ok&&r.score===100&&api.CAMP[10].missions[0].steps.some(s=>/Protect the garage/.test(s.t)));}}
if(want.includes('def')){const api=env.env.api;const D=api.CAMP.findIndex(c=>c.def);const run=(o,v)=>quiet(()=>env.play(D,1,'good',Object.assign({variant:v||'A'},o||{})));
  const load=(v,tier)=>{global.window.FORCE_V={[D]:v};api.setTier(tier===undefined?1:tier);api.loadCampaign(D);global.window.FORCE_V=undefined;api.$('brief-go').onclick();return api.S;};
  const indep=(V,S)=>{const f=api.totalFlow();return V.hyd-(S.cavDone&&!S.cavBack?V.drop:0)-f*(V.mainK*(S.sup2&&S.sup2Other?0.5:1)+V.hoseK*(S.sup2?0.25:1));};
  report('def','the defensive fire is scenario 12 (appended) with three layouts and Engine 10-2\'s 1,250 gpm rating',D===11&&api.VARIANTS[11].length===3&&api.CAMP[11].rated===1250);
  {let bad=0,n=0;for(const V of api.VARIANTS[11]){const S=load(V.id);S.pump=true;S.supply=S.hydrant=S.bled=true;S.miv=100;S.ttp=false;for(const st of [[false,false],[true,false],[true,true]]){S.sup2=st[0];S.sup2Other=st[1];for(const o of [[50,0],[100,50],[100,100]]){S.valves.deck.open=o[0];S.valves.rear3.open=o[1];S.set=138;S.mode='psi';for(let i=0;i<8;i++)api.tick(0.25);n++;if(Math.abs(api.residual()-indep(V,S))>0.01)bad++;}}}
   report('def','the hydrant residual matches an independent recalculation from each layout\'s main and hose numbers, with one or two supply lines, same main or another (27 states)',bad===0,`${bad} of ${n} off`);}
  {const S=load('A');S.pump=true;S.supply=S.hydrant=S.bled=true;S.miv=100;S.ttp=false;S.sup2=true;S.hydCap=200;S.mode='rpm';S.rpm=2400;S.valves.deck.open=100;S.valves.rear3.open=100;for(let i=0;i<8;i++)api.tick(0.25);const f1=api.totalFlow(),p1=S.psi;const c=api.CAMP[D];const keep=c.rated;c.rated=1e9;for(let i=0;i<8;i++)api.tick(0.25);const p2=S.psi,f2=api.totalFlow();c.rated=keep;
   report('def','past the 1,250 gpm rating the discharge pressure sags (same engine speed, same valves)',f2>1250&&p1<p2-20,`${Math.round(f2)} gpm unrated at ${Math.round(p2)} psi; rated it sags to ${Math.round(p1)} psi`);}
  {const V=api.VARIANTS[11].find(v=>v.id==='B');const f=1100;const same=V.hyd-f*(V.mainK+V.hoseK*0.25),other=V.hyd-f*(V.mainK*0.5+V.hoseK*0.25),one=V.hyd-f*(V.mainK+V.hoseK);
   const r1=run({},'B'),r2=run({choiceAt:{'Residual dropping':'bad'}},'B');
   report('def','layout B (a dead-end main): at about 1,100 gpm one line or a second line from the same hydrant leaves the intake under 20, a line from another main brings it over 20; choosing the same hydrant costs 10 and Engine 12-1 lays the other-main line 20 seconds later',one<20&&same<20&&other>20&&r1.ok&&r1.score===100&&r2.ok&&r2.score===90,`one ${one.toFixed(1)}, same ${same.toFixed(1)}, other ${other.toFixed(1)}; ${r1.score} / ${r2.score}`);}
  {const S=load('A',0);S.hydCap=75;let ok=0,n=0;for(const re of [74,70,66,60,52,40]){S.pdQ={st:75,re};const g=api.CAMP[D].missions[1].steps.find(s=>s.dec).dec.opts.find(o=>o.r==='good');const d=(75-re)/75*100;const want=(d<=10?'Three more':d<=15?'Two more':d<=25?'One more':'No more')+' like it';n++;if(g&&g.t===want)ok++;}S.pdQ=null;
   report('def','the percent-drop card\'s right answer matches the rule recalculated independently (0–10 % three more, 11–15 two, 16–25 one, over 25 none)',ok===n,`${ok} of ${n}`);}
  {const S=load('A');const where=api.CAMP[D].missions[2].steps.find(s=>s.dec).dec;S.set=120;S.lastChoiceT=where.opts.find(o=>/Throttle up/.test(o.t)).t;where.after();
   report('def','choosing to throttle up really throttles up (rule 14): the set point rises 30 psi and the feedback names supply, not throttle, as the fix',S.set===150&&/More supply, not more throttle/.test(where.opts.find(o=>/Throttle up/.test(o.t)).why));}
  {const S=load('A');S.pump=true;S.supply=S.hydrant=S.bled=true;S.miv=100;S.ttp=false;S.sup2=true;S.mode='psi';S.set=138;S.valves.deck.open=50;S.valves.rear3.open=100;for(let i=0;i<20;i++)api.tick(0.25);const p0=S.psi,r0=S.rpm;
   S.mission=3;api.CAMP[D].missions[3].onStart();for(let i=0;i<24;i++)api.tick(0.25);const p1=S.psi,r1=S.rpm,res=api.intakeVal(),sc0=S.score;const early=S.incidents.some(x=>/Collapsed the hydrant/.test(x));for(let i=0;i<100;i++)api.tick(0.25);const late=S.incidents.some(x=>/Collapsed the hydrant/.test(x));
   report('def','cavitation is real: with a second engine on the main the intake drops under 10, the governor climbs in RPM while the discharge falls; the penalty waits 15 seconds for the engineer to read it, then costs 10',res<10&&p1<p0-15&&r1>=r0&&!early&&late,`intake ${res.toFixed(1)}, ${Math.round(p0)}→${Math.round(p1)} psi, ${Math.round(r0)}→${Math.round(r1)} rpm, hyd ${api.supplied().hyd} def ${!!api.CAMP[S.camp].def} camp ${S.camp} cav ${S.cavDone} t ${S.t}`);}
  {const r=run({choiceAt:{'Reading cavitation':'bad'}}),r2=run();report('def','reading cavitation as a governor problem costs 10; a crew that reads it, throttles back and recovers scores 100',r.ok&&r.score===90&&r2.ok&&r2.score===100,`${r.score} / ${r2.score}`);}
  {const r=run({inject:{f:'collapse',mission:2,at:24}});report('def','instructor: the collapse zone grows; the card and two spliced steps (shut the monitor down, recharge it) are answered at the panel and the run is marked',r.ok&&r.injected===true&&r.score===100&&(api.load().log||[]).slice(-1)[0].inst===1,`score ${r.score}, injected ${r.injected}`);}
  {const r=quiet(()=>env.play(D,0,'good',{variant:'C'}));report('def','layout C adds the 2½" exposure line on the tire shop, all three streams in band near the pump\'s rating',r.ok&&r.score===100&&api.CAMP[D].missions[2].steps.some(s=>/Open #2 rear/.test(s.t)));}}

if(want.includes('fill')){const api=env.env.api;const F=api.CAMP.findIndex(c=>c.fillSite);const run=(o,v)=>quiet(()=>env.play(F,1,'good',Object.assign({variant:v||'A'},o||{})));
  const load=v=>{global.window.FORCE_V={[F]:v};api.setTier(1);api.loadCampaign(F);global.window.FORCE_V=undefined;api.$('brief-go').onclick();return api.S;};
  const prime=S=>{S.pump=true;S.hardSuction=true;S.ttp=false;for(const k in S.valves)S.valves[k].open=0;S.mode='rpm';S.rpm=1150;};
  report('fill','the fill site is scenario 13 (appended) with three layouts: a good pond, a plugged dry hydrant, ice at 10°F',F===12&&api.VARIANTS[12].length===3&&api.VARIANTS[12][1].clog&&api.VARIANTS[12][2].ice&&api.VARIANTS[12][2].cold);
  {const S=load('B');prime(S);api.$('s-primer').onclick();for(let i=0;i<40;i++)api.tick(0.25);const stuck=!S.primed&&S.vac>=20&&S.clogSaid;api.$('s-primer').onclick();const n0=api.RADIO_N();api.$('dh-flush').onclick();const refused=S.flushT<=0&&api.RADIO_N()===n0+1;
   api.$('s-ttp').onclick();api.$('dh-flush').onclick();for(let i=0;i<40;i++)api.tick(0.25);const cleared=!S.dhClog;api.$('s-ttp').onclick();S.vac=0;api.$('s-primer').onclick();for(let i=0;i<60;i++)api.tick(0.25);
   report('fill','layout B: the primer pulls high vacuum with no water (plugged, not leaking); a back-flush needs the pump, tank water and the primer off; after it the pump primes',stuck&&refused&&cleared&&S.primed,`stuck ${stuck}, refused ${refused}, cleared ${cleared}, primed ${S.primed}`);}
  {const r=run({choiceAt:{'High vacuum, no water':'bad'}},'B'),r2=run({},'B');report('fill','reading the plugged dry hydrant as an air leak costs 10; the right read scores 100',r.ok&&r.score<=90&&r2.ok&&r2.score===100,`${r.score} / ${r2.score}`);}
  {const S=load('C');const n0=api.RADIO_N();api.$('s-hard').onclick();const refused=!S.hardSuction&&api.RADIO_N()===n0+1;api.$('dh-ice').onclick();for(let i=0;i<24;i++)api.tick(0.25);api.$('s-hard').onclick();
   report('fill','layout C: the hard suction cannot go on a frozen cap (nothing to connect to); clearing the ice takes about 5 seconds, then it connects; the cold-weather freeze rules apply',refused&&!S.dhIce&&S.hardSuction&&api.CAMP[F].cold===true);}
  {const S=load('A');prime(S);S.primed=true;S.fill=false;for(let i=0;i<120;i++)api.tick(0.25);const lost=!S.primed&&S.incidents.some(x=>/drained back/.test(x));const T=load('A');prime(T);T.primed=true;T.fill=true;for(let i=0;i<120;i++)api.tick(0.25);
   report('fill','between tankers, water that stops moving lets the dry hydrant drain back (prime lost, 5); with the tank fill cracked it stays primed',lost&&T.primed,`lost ${lost}, kept ${T.primed}`);}
  {const S=load('A');prime(S);S.primed=true;S.tkOn=true;S.tk={n:1,gal:1990,cap:2000,arr:S.t,full:false,over:0};S.relayLine=true;S.mode='psi';S.set=60;S.valves.rear4.open=100;for(let i=0;i<40;i++)api.tick(0.25);const over=S.incidents.some(x=>/Overfilled/.test(x));
   const T=load('A');prime(T);T.primed=true;T.mode='psi';T.set=60;T.valves.rear4.open=100;for(let i=0;i<8;i++)api.tick(0.25);api.setValve('rear4','close');const hammer=T.incidents.some(x=>/Water hammer — gate the fill line down/.test(x));
   const U=load('A');prime(U);U.primed=true;U.mode='psi';U.set=60;U.valves.rear4.open=100;for(let i=0;i<8;i++)api.tick(0.25);['gate','gate','gate','close'].forEach(a=>api.setValve('rear4',a));const soft=!U.incidents.some(x=>/Water hammer/.test(x));
   report('fill','flowing more than 5 seconds past full overfills the tanker (5); closing the fill line hard is water hammer (5); gating it down first costs nothing',over&&hammer&&soft,`over ${over}, hammer ${hammer}, gated ${soft}`);}
  {const S=load('A');S.lastFillGpm=820;S.fillQ=null;const st=api.CAMP[F].missions[3].steps[0];st.f();const o=st.dec.opts;const h=Math.round(2000/820*2)/2;const want=Math.floor(h)+':'+(h%1?'30':'00')+' min';
   report('fill','the fill-time card is computed from the tanker size and the measured fill rate (2,000 gal at 820 gpm), checked against an independent recalculation, options fixed once',o.find(x=>x.r==='good').t===want&&JSON.stringify(o)===JSON.stringify(st.dec.opts)&&new Set(o.map(x=>x.t)).size===3,o.map(x=>x.t).join(' / '));}
  {const r=run();const b=api.$('done-body').innerHTML;report('fill','three tankers filled with turn times recorded; the debrief gives each, the average and the modeled target',r.ok&&r.score===100&&api.S.turns.length===3&&/Turn times:/.test(b)&&/modeled/.test(b),`turns ${api.S.turns.map(t=>t.toFixed(1)).join(' ')}`);}
  {const S=load('A');S.mission=3;const m=api.CAMP[F].missions[3];const sd=api.stepsDone();sd.length=0;m.steps.forEach(()=>sd.push(false));sd[0]=true;S.running=true;S.briefing=false;S.tkOn=true;S.tk=null;S.filled=1;S.nextTk=S.t+20;S.primed=true;S.pump=true;S.hardSuction=true;S.fill=true;const t0=S.t,on=api.ffStep()===1;api.ffRun();
   report('fill','fast-forward is offered while waiting for the next tanker (recirculating) and stops when it pulls onto the pad',on&&!!S.tk&&S.t-t0>=19&&S.t-t0<=22,`ran ${(S.t-t0).toFixed(1)} s`);}
  {const r=run({inject:{f:'silt',mission:3,at:4}});report('fill','instructor: silt plugs the dry hydrant between tankers; the spliced steps (close up, back-flush, re-prime) bring it back and the run still scores 100, marked',r.ok&&r.injected===true&&r.score===100&&(api.load().log||[]).slice(-1)[0].inst===1,`score ${r.score}, injected ${r.injected}`);}
  {const r=run({inject:{f:'pair',mission:2,at:20}});report('fill','instructor: two tankers arrive together; staging the second one in the lane is the right call',r.ok&&r.injected===true&&r.score===100,`score ${r.score}, injected ${r.injected}`);}}

if(want.includes('omp')){const api=env.env.api;const O=api.CAMP.findIndex(c=>c.omp);const c=api.CAMP[O];const all=c.story+' '+c.outcome+' '+c.source;
  const play=JSON.stringify(c.missions.map(m=>[m.title,typeof m.intro==='function'?m.intro():m.intro,m.steps.map(s=>[s.t,s.dec&&[typeof s.dec.q==='function'?s.dec.q():s.dec.q,s.dec.opts,s.dec.real]])]));
  report('omp','One Meridian Plaza is scenario 14, a Real Save with one fixed record (no layouts) and no scripted faults on any tier (Chaos plays like Recall)',O===13&&c.real&&!api.VARIANTS[13]&&c.missions.every(m=>!m.faults));
  {const need=['8:23 p.m.','passerby at a pay phone','8:27','Engine 43 arrived at 8:31 with fire showing from one window','second alarm went out at 8:33','Linseed oil-soaked rags left by a contractor in a vacant office','emergency generator failed','two electric fire pumps lost power','"effectively prevented the increased pressure in the standpipes from being discharged through the valves."','index 80 delivered 55 to 57 psi, about 40 to 45 psi at the nozzle','index of 88 to 91','150 to 158','2½-inch lines with straight-bore nozzles','1¾-inch hose with automatic fog nozzles needing 100 psi','several hours into the fire','a sprinkler contractor adjusted them','1:17 a.m.','about 2:15 a.m.','They had run out of air','up the west stair to the 24th floor','12th alarm went out at 2:21 a.m.','51 engine companies, 15 ladder companies, 11 specialized units and about 316 firefighters, with no mutual aid','Twenty-four firefighters were injured','At 7:00 a.m., after about 11 hours','pancake collapse','complete by 7:30','"the most courageous safety decision."','10 sprinklers','30, 31, 34 and 35','Eight floors were consumed','more than 19 hours','3:01 p.m. on February 24','"an essentially impossible situation and did a commendable job."','approved in the fall of 1992 for the 1993 edition','all existing high-rise buildings by 1997','In memory of Captain David P. Holcombe, Firefighter Phyllis McAllister and Firefighter James A. Chappell, Philadelphia Fire Department Engine 11.'];
   const miss=need.filter(x=>!all.includes(x));report('omp','every fact Max had checked against USFA-TR-049 is in the story or the record, word for word where quoted, with the memorial line',miss.length===0,miss.join(' | '));}
  {const banned=[/8:37/,/about 8:40/,/1999/,/dismantl/i,/white paper/i,/Life Safety/i,/demolish/i];const hit=banned.filter(r=>r.test(all+play));report('omp','dropped details stay out: no 8:37, no "about 8:40", nothing about the building\'s demolition, no valve-industry white paper as a source',hit.length===0,hit.join(' '));}
  report('omp','the source is the USFA report with its authors; the engine and every pressure are labeled modeled',/Routley, Jennings and Chubb/.test(c.source)&&/USFA-TR-049/.test(c.source)&&/modeled/.test(c.story)&&c.missions.filter(m=>m.steps.some(s=>/psi \(modeled/.test(s.t))).length>=2);
  report('omp','no real person is portrayed in play: Engine 11 and its members appear only in the record, never in a radio line, decision or step',!/Engine 11|Holcombe|McAllister|Chappell|Captain is down|captain was down/.test(play)&&/Engine 11/.test(c.outcome));
  {const m=c.missions[1];report('omp','the pressure-reducing valve lesson: on the fire floors the crews report weak streams even when the connection pressure is right',/weak/.test(String(m.chat.ok))&&/Still weak at the nozzle/.test(m.chat.ok.toString()));}
  {const r=quiet(()=>env.play(O,1,'bad'));const r2=quiet(()=>env.play(O,2,'good'));report('omp','each wrong call costs 10 and the run still finishes; a clean run on Chaos scores 100 with no faults',r.ok&&r.score===60&&r2.ok&&r2.score===100,`${r.score} / ${r2.score}`);}
  {const r=quiet(()=>env.play(O,0,'good'));const b=api.$('done-body').innerHTML;report('omp','the debrief tells the record and closes with the memorial line',r.ok&&/the most courageous safety decision/.test(b)&&/In memory of Captain David P. Holcombe/.test(b));}}
if(want.includes('balance')){const {CAMP}=env.env.api;let lo=0,sh=0,t=0,first=0;for(const c of CAMP)for(const m of c.missions)for(const s of m.steps)if(s.dec&&s.dec.opts){const L=s.dec.opts.map(x=>x.t.length),g=s.dec.opts.findIndex(x=>x.r==='good');t++;if(L[g]===Math.max(...L))lo++;else if(L[g]===Math.min(...L))sh++;}
  report('balance','right answer is not usually the longest',lo/t<=.45,`${lo} of ${t} (${Math.round(lo/t*100)}%)`);report('balance','right answer is not usually the shortest',sh/t<=.45,`${sh} of ${t} (${Math.round(sh/t*100)}%)`);
  report('balance','answer order is shuffled on screen',/d\.opts\.map\(\(o,i\)=>\[o,i\]\)\.sort\(\(\)=>Math\.random\(\)-\.5\)/.test(html));}

if(want.includes('play')){const {CAMP}=env.env.api;for(let ci=0;ci<CAMP.length;ci++){let ok=0,perfect=0;for(const tier of [0,1,2]){const r=quiet(()=>env.play(ci,tier));if(r.ok)ok++;if(r.score===100)perfect++;}
  report('play',`${short(CAMP[ci].name)}: all tiers complete`,ok===3,`${ok}/3, ${perfect}/3 perfect`);}}

if(want.includes('paths')){const {CAMP}=env.env.api;for(let ci=0;ci<CAMP.length;ci++){if(!CAMP[ci].real)continue;let ok=0;const sc=[];for(const ch of ['partial','bad']){const r=quiet(()=>env.play(ci,0,ch));if(r.ok)ok++;sc.push(r.score);}
  report('paths',`${short(CAMP[ci].name)}: completable after wrong answers`,ok===2,`scores ${sc.join(' / ')}`);}}

if(want.includes('human')){const {CAMP}=env.env.api;for(let ci=0;ci<CAMP.length;ci++){let ok=0;const sc=[];for(const tier of [0,1,2]){const r=quiet(()=>env.play(ci,tier,'good',{human:true}));if(r.ok)ok++;sc.push(r.score);}
  report('human',`${short(CAMP[ci].name)}: completes at human pace`,ok===3,`scores ${sc.join(' / ')}`);}}

for(const [sec,file,marker] of [['checks','qa2.js','ALL CHECKS PASSED'],['guide','qa_guide.js','ALL GUIDE CHECKS PASSED']])if(want.includes(sec)){
  let out='';try{out=execFileSync(process.execPath,[path.join(__dirname,file)],{cwd:path.join(__dirname,'..'),encoding:'utf8',timeout:240000});}catch(e){out=(e.stdout||'')+(e.stderr||'');}
  const fails=out.split('\n').filter(l=>/✗/.test(l));report(sec,`${file}: ${sec==='checks'?'chaos faults, wrong-answer paths, pacing, cost':'guide cards, links, penalties'}`,out.includes(marker),fails.slice(0,3).map(x=>x.trim()).join(' | '));}

if(want.includes('stress')){const {CAMP}=env.env.api;let total=0,bad=0;for(let ci=0;ci<CAMP.length;ci++)for(let k=0;k<20;k++)for(const tier of [0,1,2]){total++;if(!quiet(()=>env.play(ci,tier)).ok)bad++;}
  report('stress',`${total} randomized playthroughs`,bad===0,bad?bad+' failed':'');}

if(want.includes('fuzz')){const {boot}=require('./qa_mock.js');const ids=[...html.matchAll(/<button[^>]*id="([^"$]+)"/g)].map(m=>m[1]);let crashes=0;const errs=[];const runs=want.length<=4?20:60;
  for(let run=0;run<runs;run++){const {api}=boot();const {$,CAMP,S}=api;api.setTier(run%3);api.loadCampaign(run%CAMP.length);
    try{for(let i=0;i<1500;i++){if(api.DEC()){$('dec-opts').onclick({target:{closest:()=>({dataset:{i:String(i%3)}})}});$('dec-go').onclick();}
      if(Math.random()<.4){const b=$(ids[Math.floor(Math.random()*ids.length)]);b.onclick&&b.onclick();}S.running=S.running||Math.random()<.5;api.tick(.25);
      for(const k of ['psi','rpm','tank','score'])if(!Number.isFinite(S[k]))throw new Error('non-finite '+k);}}catch(e){crashes++;errs.push(e.message);}}
  report('fuzz',`${runs} runs × 1500 random taps, no crashes or NaN`,crashes===0,crashes?[...new Set(errs)].slice(0,3).join(' | '):'');}

if(want.includes('syntax')){// final sweep M1: CSV cells safe and quoted, wrong-shape data never bricks the menu, older saved-data formats still load
  const {boot}=require('./qa_mock.js');
  {const {api,els}=boot({'e102-pump-trainer':JSON.stringify({name:'=HYPERLINK("http://x","x")',scen:{0:{best:88,runs:1,last:'2026-10-01T00:00:00Z',tier:1,level:1}},math:{right:3,total:4}})});api.showMenu();els['b-progress'].onclick();global.__blob='';els['b-export'].onclick();const csv=global.__blob||'';const lines=csv.split('\n');
   const b2=boot({'e102-pump-trainer':JSON.stringify({name:'"a","b"',scen:{},math:{right:0,total:0}})});b2.api.showMenu();b2.els['b-progress'].onclick();global.__blob='';b2.els['b-export'].onclick();const csv2=global.__blob||'';const Q=String.fromCharCode(34);
   report('syntax','CSV: a name typed as a formula is defused, every cell is quoted, and a name with quotes no longer shifts the columns (23 rows: header, 14 scenarios, lesson, 6 drills incl. the pump math set, lifetime pump math)',/^"'=HYPERLINK\(""http:\/\/x"",""x""\)","Residential structure fire","Recall","1","88","2026-10-01","1"$/.test(lines[1])&&lines.length===23&&csv2.split('\n')[1].startsWith(Q+Q+Q+'a'+Q+Q+','+Q+Q+'b'+Q+Q+Q+',"Residential structure fire"'),lines[1]+' · '+lines.length+' lines');}
  {let ok=true,why='';for(const bad of ['[]','5','{}','{"scen":[],"log":5,"math":"x"}','{"log":[null,{"i":0,"score":80,"tier":0,"d":"2026-10-01T00:00:00Z"}]}']){try{const b=boot({'e102-pump-trainer':bad});b.api.showMenu();b.api.dueInfo(0);b.api.recordX('drill','friction',80);const p=b.api.load();if(!p.scen||typeof p.scen!=='object'||!Array.isArray(p.extra)||p.extra.slice(-1)[0].id!=='friction')throw new Error('bad shape after '+bad);if(p.log&&p.log.some(r=>!r))throw new Error('null run kept for '+bad);}catch(e){ok=false;why=e.message;}}
   report('syntax','wrong-shape saved data ([] / 5 / {} / lists where objects belong / a null run) opens the menu and still records',ok,why);}
  {const dir=path.join(__dirname,'fixtures');let n=0,bad=[];for(const f of fs.readdirSync(dir).filter(x=>x.startsWith('ctl-')&&x.endsWith('.json'))){const data=fs.readFileSync(path.join(dir,f),'utf8');const before=JSON.parse(data);try{const b=boot({'e102-pump-trainer':data});b.api.showMenu();b.els['b-progress'].onclick();global.__blob='';b.els['b-export'].onclick();b.api.recordX('drill','friction',80);const after=b.api.load();if(Array.isArray(before.log)&&(!Array.isArray(after.log)||after.log.length<before.log.length))throw new Error('log shrank');if(Object.keys(after.scen).length<Object.keys(before.scen||{}).length)throw new Error('scen shrank');if(before.name!==undefined&&after.name!==before.name)throw new Error('lost name');if(!/Name/.test(global.__blob))throw new Error('no csv');n++;}catch(e){bad.push(f+': '+e.message);}}
   report('syntax',`older saved-data formats (${n} fixtures, 2.2.1 to 2.10.0 and an unknown id) open the menu, export and keep every field when a new run is added`,n>=5&&!bad.length,bad.join(' | ')||`${n} fixtures`);}
}
if(want.includes('syntax')){// final sweep M2: the gauges are drawn once and only the needle moves; nothing is redrawn on the menu; Resume takes the wake lock again
  const {boot}=require('./qa_mock.js');
  {const {api,els}=boot();const g=els['g-master'];let writes=0,v='';Object.defineProperty(g,'innerHTML',{get:()=>v,set:x=>{v=x;writes++;},configurable:true});const built=!!g._face;let moves=0;if(g._needle)g._needle.setAttribute=()=>{moves++;};api.loadCampaign(0);api.S.psi=100;api.render();api.S.psi=140;api.render();for(let i=0;i<40;i++)api.render();
   report('syntax','gauges: the dial face is built once at boot; forty renders rebuild nothing, only the needle moves',built&&writes===0&&moves>=4,`built ${built}, rebuilds ${writes}, needle moves ${moves}`);}
  report('syntax','the 250 ms loop redraws nothing while no scenario is active (battery)',/if\(S\.running\)tick\(dt\);else if\(S\.active\)render\(\);/.test(html)&&/\nrender\(\);setInterval\(/.test(html));
  {const B=boot();let req=0,rel=0;const lock={addEventListener(){},release(){rel++;return Promise.resolve();}};navigator.wakeLock={request(){req++;return {then(f){f(lock);return {catch(){}};}};}};B.api.loadCampaign(0);B.api.showBrief();B.api.$('brief-go').onclick();B.api.showMenu();const a=[req,rel];B.els['b-resume'].onclick();const b=[req,rel];delete navigator.wakeLock;
   report('syntax','Resume after Menu takes the wake lock again',a[0]===1&&a[1]===1&&b[0]===2,`menu ${a} resume ${b}`);}
}
console.log(`\n${results.length-failed}/${results.length} checks passed · ${Math.round((Date.now()-T0)/1000)} s`);process.exit(failed?1:0);
